# Generated by Django 2.0.3 on 2018-03-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lntlat',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
