# Generated by Django 2.0.3 on 2018-03-31 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_lntlat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='lntlat',
            new_name='lnglat',
        ),
    ]
